// Code generated by mockery v2.32.4. DO NOT EDIT.

package todousecasemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	types "github.com/winartodev/go-grpc/types"
)

// TodoUsecaseInterface is an autogenerated mock type for the TodoUsecaseInterface type
type TodoUsecaseInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, data
func (_m *TodoUsecaseInterface) Create(ctx context.Context, data types.Task) (*types.Task, error) {
	ret := _m.Called(ctx, data)

	var r0 *types.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Task) (*types.Task, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.Task) *types.Task); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.Task) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TodoUsecaseInterface) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *TodoUsecaseInterface) GetAll(ctx context.Context) ([]types.Task, error) {
	ret := _m.Called(ctx)

	var r0 []types.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]types.Task, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []types.Task); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TodoUsecaseInterface) GetByID(ctx context.Context, id int64) (*types.Task, error) {
	ret := _m.Called(ctx, id)

	var r0 *types.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*types.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *types.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *TodoUsecaseInterface) Update(ctx context.Context, id int64, data types.Task) (*types.Task, error) {
	ret := _m.Called(ctx, id, data)

	var r0 *types.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, types.Task) (*types.Task, error)); ok {
		return rf(ctx, id, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, types.Task) *types.Task); ok {
		r0 = rf(ctx, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, types.Task) error); ok {
		r1 = rf(ctx, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTodoUsecaseInterface creates a new instance of TodoUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoUsecaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoUsecaseInterface {
	mock := &TodoUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
